kind: Deployment
apiVersion: apps/v1
metadata:
  name: clusterlifecycle-state-metrics
  namespace: open-cluster-management
spec:
  template:
    spec:
      containers:
      - name: clusterlifecycle-state-metrics
        image: quay.io/open-cluster-management/clusterlifecycle-state-metrics:2.2.0-PR1-f87eef989b121a7bd821c2ddc306fdf5a2a3d3aa
