apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: ocm-state-metrics
  name: ocm-state-metrics
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    scrapeTimeout: 20s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      # serverName: ocm-state-metrics.open-cluster-management.svc
      insecureSkipVerify: true
  jobLabel: ocm-app
  selector:
    matchLabels:
      ocm-app: ocm-state-metrics
  namespaceSelector:
    matchNames:
      - open-cluster-management